from . import account_journal
from . import catalogos
from . import catalogos_sat
from . import hr
from . import res_bank
from . import employee
from . import res_company
from . import hr_other_inputs
from . import hr_payslip
from . import hr_payslip_cfdi
from . import hr_payroll
from . import res_partner
from . import hr_mov_nomina
from . import hr_attendance
from . import hr_holidays
from . import res_config_settings
from . import hr_transfer
from . import salary_rule
